### ISSUE TITLE
Is there any update in this package?

### ISSUE THREAD

**Issue by hydrogeohc** [giswqs/geospatial#14]
* geospatial version:
* Python version:
* Operating System:

### Description

Describe what you were trying to get done.
Tell us what happened, what went wrong, and what you expected to happen.

### What I Did

```
Paste the command(s) you ran and the output.
If there was a crash, please include the traceback here.
```

**Comment by giswqs** [comment]
The geospatial package is a collection of Python packages for geospatial analysis and interactive mapping, making it easier to install commonly used geospatial packages with only one line of code. The package itself does not provide any additional functionality. 
https://geospatial.gishub.org/installation
