### ISSUE TITLE
Suggestions for adding packages to geospatial

### ISSUE THREAD

**Issue by giswqs** [giswqs/geospatial#16]
If you would like to suggest new packages to be added to the geospatial stack, please leave comments down here. Here are the steps:

First, check https://geospatial.gishub.org/#installed-packages and see if the suggested packages are listed on the list. If they are already listed, then you can skip the following steps.

Second, search the suggested packages on https://conda-forge.org/feedstock-outputs and make sure they can be found there. If not, that means the suggested packages are not available on conda-forge. If this is the case, then they cannot be added to the geospatial stack. Then you can skip the following step.

Third, leave the names of suggested packages here if they meet the above requirements.

**Comment by giswqs** [comment]
pysal would be a good addition. However, one of the pysal dependencies fails `pip check`. Therefore, pysal can't be added to the geospatial stack until the issue is resolved by the pointpats maintainers. See https://github.com/pysal/pointpats/issues/80

**Comment by davemlz** [comment]
Hi Prof. Wu,

This is a very nice idea!

Here are some suggestions:

Earth Engine:
- `wxee`
- `eemont`

STAC:
- `stackstac`
- `planetary_computer`
- `radiant_mlhub`
- `easystac` (It would install the above mentioned in STAC)

Visualizations:
- `proplot`
- `eomaps`
- `xmovie`

EO processing:
- `spyndex`
- `s2cloudless`
- `rasterstats`

ML:
- `torchgeo`
- `verde`

**Comment by dkerkow** [comment]
Hi, thanks for setting this up!

I would suggest including https://anaconda.org/conda-forge/geoalchemy2, as you have included SQLAlchemy anyway. I use the PyPI version in a couple of production apps.

**Comment by giswqs** [comment]
@davemlz Good suggestions. I can probably add all of them except `touchgeo` and `verde`. Adding these two needs to download 199 packages with 643 MB, which can be time-consuming for users. I want the package to be as inclusive as possible, but in the meantime, I also want to make sure that it is relatively fast and easy to install. 

![image](https://user-images.githubusercontent.com/5016453/161755543-318a8bcb-b0f4-4cf0-9346-cf5c4dfbb861.png)

**Comment by giswqs** [comment]
@davemlz The `geospatial-ml` package is now available on PyPI. It should be available on conda-forge in a few days. For now, it only contains four packages. Suggestions for adding more geospaital packages for machine learning are welcome.  

https://github.com/giswqs/geospatial-ml

PS: Initially, I used `geoml` as the package name, but PyPI does not allow that due to another existing package with a similar name.

```
    - geospatial
    - scikit-learn
    - torchgeo
    - verde
```

**Comment by davemlz** [comment]
That's great! I will open an Issue with some suggestions there.

Thanks, Prof. Wu!

**Comment by joemcglinchy** [comment]
I'd like to suggest `pystac-client` and `odc-stac`

**Comment by giswqs** [comment]
@joemcglinchy  `pystac-client` is ready on the list. See https://geospatial.gishub.org/#installed-packages
I will add `odc-stac` shortly.

**Comment by joemcglinchy** [comment]
oh my bad, i was looking at the recipe not the installed packages. thanks!

**Comment by giswqs** [comment]
@joemcglinchy No problem. The recipe only lists the top-level dependencies. I did not list secondary dependencies to avoid the recipe getting too long.

**Comment by giswqs** [comment]
@joemcglinchy `odc-stac` is now available through the geospatial package on PyPI. It should be available on conda-forge in a few hours. https://github.com/conda-forge/geospatial-feedstock/pull/9/files

**Comment by geowest11** [comment]
The h3 package for working with Uber's hexagonal grid would be nice to have in there. Also, the cenpy package for census data and geographies.

**Comment by giswqs** [comment]
@geowest11 Thank you for the suggestions. cenpy and h3 have been added. Should be available on conda-forge in a few hours.

**Comment by RichardScottOZ** [comment]
Geocube for a nice rasterising api

**Comment by giswqs** [comment]
@RichardScottOZ geocube has been added. Should be available on conda-forge soon. 
https://github.com/conda-forge/geospatial-feedstock/pull/13

**Comment by jameshgrn** [comment]
Hey Qiusheng! What do you think about supporting [sliderule?](http://icesat2sliderule.org/) It's for icesat-2 data retrieval. I'm not sure it's possible, but if its easy enough, would be great! 

Also, cheers. I said this on twitter but it's worth repeating—this is a much needed contribution to the community, thanks again!

**Comment by Pancheliuga** [comment]
First off, thank you for your giant impact and contribution to Geospatial!

I would like to see "contextily" in your package

**Comment by giswqs** [comment]
@jameshgrn @Pancheliuga Both contextily and sliderule have been added. Should be available shortly. 
https://github.com/conda-forge/geospatial-feedstock/pull/14/files

**Comment by monocilindro** [comment]
Qiusheng, what do you think of adding pygmt? It is based on Generic Mapping Tools, a widely used tool in Geophysics 
Great work of yours, BTW

**Comment by giswqs** [comment]
@monocilindro Thanks for the suggestion. I am a bit hesitant to add pygmt. It has several large dependencies, which will add 172 MB to geospatial. I am trying to keep geospatial relatively small and easy to install. 

![image](https://user-images.githubusercontent.com/5016453/164754889-42541992-ce8f-4907-9ffc-bdf3ee7dce19.png)

**Comment by ArterialMapping** [comment]
Would it be possible to add routingpy? 

https://github.com/gis-ops/routing-py

https://routingpy.readthedocs.io/en/latest/#

**Comment by giswqs** [comment]
@ArterialMapping It appears that `routingpy` requires `ipykernel >=5.3.4,<6`, which was released over a year ago. Many packages in the geospatial stack require a much newer version of ipykernel. `routingpy` needs to bring ipykernel up to date before it can be added to geospatial. 

https://github.com/conda-forge/routingpy-feedstock/blob/c32ee1d1500c3f6bbda723b342886b9b45488513/recipe/meta.yaml#L30
![image](https://user-images.githubusercontent.com/5016453/165417888-5b7a03fb-14e6-4cd4-a13c-217ebe59c9a8.png)

[![image](https://user-images.githubusercontent.com/5016453/165417350-01364ee8-8052-4807-8be2-4430bd20c045.png)

**Comment by nilsnolde** [comment]
For routingpy we don’t support conda anymore unless community steps up for maintenance. It’s a pointless hassle for us, as a python-only lib. 

I like this consolidation though. Is conda support a requirement to add to geospatial?

**Comment by giswqs** [comment]
@nilsnolde Yes, supporting conda is a requirement to add to geospatial. Many geospatial packages are challenging to install via pip. The advantage of using conda is that it can resolve dependency conflicts, while pip cannot. 

You can set up automerge for your package on conda-forge. It will automatically update conda-forge whenever you release a new version to PyPI. This requires minimal efforts to maintain the package on conda-forge. 
https://conda-forge.org/docs/maintainer/infrastructure.html#conda-forge-admin-please-add-bot-automerge

**Comment by nilsnolde** [comment]
thanks, think I was a bit too sleepy still this morning.. of course this is all about conda :sweat_smile: I figured there'd be some some automagic by now, my conda experience is 4-5 years ago. given the pervasiveness of conda I'll set up the workflow again and inform back again (actually we only have `requests` as actual dependency, the conda recipe is crazy outdated). thanks @giswqs and @ArterialMapping , was being pretty lazy on that one.

**Comment by giswqs** [comment]
Just added pysal. Closing this issue for now. Feel free to open a new issue if you would like to suggest new packages to be added to geospatial.

**Comment by tariah7** [comment]
Good day sir, 
I'd like to suggest PCraster be added to the list.

**Comment by giswqs** [comment]
PCRaster is not a Python package.

**Comment by andyrich** [comment]
hyriver
https://hyriver.readthedocs.io/en/latest/

**Comment by ravish-bapna** [comment]
Please explore the possibility of adding "earthaccess" package; more info available at https://pypi.org/project/earthaccess/

**Comment by edwardpmorris** [comment]
PDAL (Python bindings) for processing PointClouds (Lidar data). Although admittedly its really a wrapper and also depends on GDAL. 
![image](https://github.com/opengeos/geospatial/assets/820997/656bae87-45e8-4fbf-8d54-45d5846047f1)

**Comment by giswqs** [comment]
@edwardpmorris pdal has been added. https://github.com/conda-forge/geospatial-feedstock/pull/37

**Comment by radwinskis** [comment]
Hi @giswqs I would like to suggest adding RadGEEToolbox to geospatial for Google Earth Engine processing workflows: [conda-forge/radgeetoolbox-feedstock](https://github.com/conda-forge/radgeetoolbox-feedstock)

Thanks!

**Comment by isaldiviagonzatti** [comment]
xesmf for regridding. Or do any of the included packages offer a better solution?
