### ISSUE TITLE
Add FileGDB driver

### ISSUE THREAD

**Issue by evan-blaisdell** [giswqs/geospatial#22]
The FileGDB driver for reading and writing ESRI File Geodatabases would be very useful. Currently, only the OpenFileGDB is included, which is read-only.

https://gdal.org/drivers/vector/filegdb.html

**Comment by giswqs** [comment]
What is the package name on [PyPI](https://pypi.org/) and [conda-forge](https://conda-forge.org/feedstock-outputs/)? I can't find it.

**Comment by evan-blaisdell** [comment]
The driver files are available here:

https://github.com/Esri/file-geodatabase-api

Evan M. Blaisdell
Developer
Mission Accelerator Group
Mobile: +1.301.787.2067
***@***.******@***.***>
***@***.***<https://www.maxar.com/?utm_source=email-signature&utm_medium=email>
***@***.******@***.******@***.******@***.***<https://www.instagram.com/maxartechnologies/>

**Comment by evan-blaisdell** [comment]
Understood. Thank you sir.

Evan M. Blaisdell
Developer
Mission Accelerator Group
Mobile: +1.301.787.2067
***@***.******@***.***>
***@***.***<https://www.maxar.com/?utm_source=email-signature&utm_medium=email>
***@***.******@***.******@***.******@***.***<https://www.instagram.com/maxartechnologies/>
